# Generated by Django 5.2.3 on 2025-06-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersearchingdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiseaseName', models.CharField(max_length=200)),
                ('DiseaseImage', models.ImageField(upload_to='images/')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
