# Generated by Django 5.2.3 on 2025-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('farmingexperience', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='userprofile/')),
            ],
        ),
    ]
