# Generated by Django 5.2.3 on 2025-07-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
