# Generated by Django 5.2.3 on 2025-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=200)),
                ('userfarmingexperienxe', models.CharField(max_length=200)),
                ('userimage', models.ImageField(upload_to='userprofile/')),
            ],
        ),
    ]
