# Generated by Django 5.2.3 on 2025-07-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userfarmingexperienxe',
            new_name='userfarmingexperience',
        ),
    ]
