// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN475By1LdTB1z2NLq7h7Dku68Tprnoy8',
    appId: '1:882263488837:web:e9c8b48a999a482e98262c',
    messagingSenderId: '882263488837',
    projectId: 'tomato-guard-c1244',
    authDomain: 'tomato-guard-c1244.firebaseapp.com',
    storageBucket: 'tomato-guard-c1244.firebasestorage.app',
    measurementId: 'G-T02YB9PGN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKUMR181RWsoIHwomft3EqwCKFAOdzqNg',
    appId: '1:882263488837:android:82f008c84ef4635198262c',
    messagingSenderId: '882263488837',
    projectId: 'tomato-guard-c1244',
    storageBucket: 'tomato-guard-c1244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVX-eOGJ2J8vUdeyGiXkioHvsCbeUsaM',
    appId: '1:882263488837:ios:e5707f1284e6f56898262c',
    messagingSenderId: '882263488837',
    projectId: 'tomato-guard-c1244',
    storageBucket: 'tomato-guard-c1244.firebasestorage.app',
    iosBundleId: 'com.example.tomatoGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVX-eOGJ2J8vUdeyGiXkioHvsCbeUsaM',
    appId: '1:882263488837:ios:e5707f1284e6f56898262c',
    messagingSenderId: '882263488837',
    projectId: 'tomato-guard-c1244',
    storageBucket: 'tomato-guard-c1244.firebasestorage.app',
    iosBundleId: 'com.example.tomatoGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN475By1LdTB1z2NLq7h7Dku68Tprnoy8',
    appId: '1:882263488837:web:636ecb5fe40f9a2898262c',
    messagingSenderId: '882263488837',
    projectId: 'tomato-guard-c1244',
    authDomain: 'tomato-guard-c1244.firebaseapp.com',
    storageBucket: 'tomato-guard-c1244.firebasestorage.app',
    measurementId: 'G-V9VQG68G6Q',
  );
}
